PRESET_STRATEGIES = {
    "00": {"id": "00", "name": "표준",       "type": "기본",     "desc": "시스템 기본 TP/SL 적용 (Vibe 보정 포함)",
           "default_tp": None, "default_sl": None},  # None이면 시스템 기본값 사용
    "01": {"id": "01", "name": "골든크로스", "type": "추세추종", "desc": "단기 MA가 장기 MA 상향 돌파 시 매수",
           "default_tp": 8.0, "default_sl": -4.0},
    "02": {"id": "02", "name": "모멘텀",     "type": "추세추종", "desc": "최근 N일 수익률 상위 종목 매수",
           "default_tp": 10.0, "default_sl": -5.0},
    "03": {"id": "03", "name": "52주신고가", "type": "돌파매매", "desc": "52주 최고가 갱신 시 매수",
           "default_tp": 12.0, "default_sl": -3.0},
    "04": {"id": "04", "name": "연속상승",   "type": "추세추종", "desc": "N일 연속 종가 상승 시 매수",
           "default_tp": 7.0, "default_sl": -4.0},
    "05": {"id": "05", "name": "이격도",     "type": "역추세",   "desc": "이동평균 대비 과열/침체 판단",
           "default_tp": 5.0, "default_sl": -3.0},
    "06": {"id": "06", "name": "돌파실패",   "type": "손절",     "desc": "전고점 돌파 후 재하락 시 손절",
           "default_tp": 4.0, "default_sl": -2.0},
    "07": {"id": "07", "name": "강한종가",   "type": "모멘텀",   "desc": "종가가 당일 고가 근처 마감 시 매수",
           "default_tp": 6.0, "default_sl": -3.5},
    "08": {"id": "08", "name": "변동성확장", "type": "돌파매매", "desc": "변동성 축소 후 급등 시 매수",
           "default_tp": 9.0, "default_sl": -4.0},
    "09": {"id": "09", "name": "평균회귀",   "type": "역추세",   "desc": "평균에서 크게 이탈 시 반대 방향 매매",
           "default_tp": 4.0, "default_sl": -3.0},
    "10": {"id": "10", "name": "추세필터",   "type": "추세추종", "desc": "장기 MA 위 상승 중이면 매수",
           "default_tp": 8.0, "default_sl": -5.0},
}
