import subprocess
import os
import re
import ast
from datetime import datetime

def get_test_descriptions():
    """ast 모듈을 사용하여 테스트 파일에서 함수명과 docstring을 정확하게 추출"""
    descriptions = {}
    test_file = "tests/test_advanced_integration.py"
    if not os.path.exists(test_file):
        return descriptions
        
    try:
        with open(test_file, "r", encoding="utf-8") as f:
            tree = ast.parse(f.read())
            
        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and node.name.startswith("test_"):
                doc = ast.get_docstring(node)
                if doc:
                    descriptions[node.name] = doc.strip()
    except Exception as e:
        print(f"Error parsing test file: {e}")
        
    return descriptions

def run_tests_and_generate_report():
    print("Starting test execution and advanced report generation...")
    
    # 1. 시나리오 설명 매핑 생성 (ast 기반)
    desc_map = get_test_descriptions()
    
    # 2. Pytest 실행 및 결과 수집
    cmd = ["pytest", "tests/test_advanced_integration.py", "-v"]
    result = subprocess.run(cmd, capture_output=True, text=True)
    
    output = result.stdout
    success = (result.returncode == 0)
    
    # 3. 테스트 결과 파싱
    table_rows = []
    lines = output.splitlines()
    for line in lines:
        # 패턴: tests/test_advanced_integration.py::ClassName::method_name PASSED
        # 또는 tests/test_advanced_integration.py::method_name PASSED
        if "::" in line and ("PASSED" in line or "FAILED" in line):
            # 메서드 이름 추출
            parts = line.split("::")
            last_part = parts[-1].split()
            method_name = last_part[0]
            status = last_part[1]
            
            desc = desc_map.get(method_name, "설명 없음")
            status_str = "✅ PASS" if status == "PASSED" else "❌ FAIL"
            
            table_rows.append(f"| {desc} | `{method_name}` | {status_str} | - |")
            
    # 4. 리포트 작성
    report_path = "docs/TEST_REPORT.md"
    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("# 🧪 AI-Vibe-Trader Test Report\n\n")
        f.write("## 📊 Summary\n")
        res_tag = "<span style='color:green; font-weight:bold;'>✅ PASS</span>" if success else "<span style='color:red; font-weight:bold;'>❌ FAIL</span>"
        f.write(f"- **Total Result**: {res_tag}\n")
        f.write(f"- **Executed at**: `{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}`\n")
        f.write(f"- **Test Suite**: `tests/test_advanced_integration.py`\n\n")
        
        f.write("## 📝 Detailed Test Scenarios\n")
        f.write("| 시나리오 명 | 테스트 메서드 | 결과 | 비고 |\n")
        f.write("| :--- | :--- | :---: | :--- |\n")
        f.write("\n".join(table_rows))
        f.write("\n\n---\n")
        f.write(f"*Generated by AI-Vibe-Trader Build Pipeline at {datetime.now().strftime('%H:%M:%S')}*\n")

    print(f"Report generation complete: {report_path}")

if __name__ == "__main__":
    run_tests_and_generate_report()
